app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import validators
from wtforms import StringField, PasswordField, BooleanField, SubmitField, RadioField, IntegerField
from wtforms.fields.core import SelectField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField
from flask_wtf import Form
from wtforms.fields.html5 import DateField

class ExampleForm(FlaskForm):
    dt = DateField("DatePicker", format="%Y-%m-%d")
    dokters = SelectField("Dokter", choices=[])
    submit = SubmitField('input')




class UpdateDocterAccount(FlaskForm):
    username = StringField("Username", 
                            validators=[DataRequired(), Length(1, 20)])

    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                        Email()])
    speciality = StringField("Speciality",
                             validators=[DataRequired(), Length(5, 60)])
    address = StringField("Address",
                             validators=[DataRequired(), Length(5, 60)])
    file_img = FileField('file')
    submit = SubmitField('Update')


class UpdatePatientAccount(FlaskForm):
    username = StringField("Username", 
                            validators=[DataRequired(), Length(1, 20)])

    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                        Email()])
    age = IntegerField("Umur", validators=[DataRequired()])
    gender = RadioField('UserType', choices=[('male', 'Pria'), ('female', 'Wanita')])
    address = StringField("Address",
                            validators=[DataRequired(), Length(5, 60)])
    file_img = FileField('file')
    submit = SubmitField('Update')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
login_manger = LoginManager()
db = SQLAlchemy()
login_manger.login_view = 'auth.login'


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hard to guess string'
    app.config["SQLALCHEMY_DATABASE_URI"]= 'sqlite:///data.sqlite'
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    bootstrap.init_app(app)
    db.init_app(app)
    login_manger.init_app(app)
    from .main import main as main_blueprinth
    app.register_blueprint(main_blueprinth)
    from .auth import auth as auth_blueprinth
    app.register_blueprint(auth_blueprinth, url_prefix='/auth')
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, forms, errors

app/main/views.py
from flask.globals import request
import datetime
import base64
from app.main.forms import UpdateDocterAccount, UpdatePatientAccount, ExampleForm
from werkzeug.utils import redirect
from app import main
from flask import render_template, redirect, url_for, g, session, flash
from . import main
from .. import db
from ..model import Appointment, Doctor, Patient
@main.before_request
def before_request():
    if 'email' in session and 'user' in session:
        if session['user'] == 'val2':
            user = Patient.query.filter_by(email=session['email']).first()
            g.user = user
        else:
            user = Doctor.query.filter_by(email=session['email']).first()
            g.user = user
    else:
        g.user = None

@main.route("/")
def index():
    if not g.user:
        return redirect(url_for('auth.login'))
    return render_template('index.html')

@main.route("/docters")
def docters():
    dokters = Doctor.query.all()
    docs =[]
    for dokter in dokters:
        dokter.image = base64.b64encode(dokter.image).decode('ascii')
    return render_template("mainapp/docters.html", dokters=dokters)

@main.route("/account", methods=["GET", "POST"])
def account():
    if "email" in session:
        image_file = None
        user = session["user"]
        form = UpdatePatientAccount() if user == "val2" else UpdateDocterAccount()
        if request.method == "GET":
            if user == "val2":
                pasien = Patient.query.filter_by(email=session["email"]).first()
                form.username.data = pasien.name
                form.email.data = pasien.email
                form.gender.data = pasien.gender
                form.age.data = pasien.age
                form.address.data = pasien.address
                if not pasien.image:
                    image_file = url_for("static", filename="karlo.jpg")
                else:
                    image_file = base64.b64encode(pasien.image).decode('ascii')
            elif user == "val1":
                dokter = Doctor.query.filter_by(email=session["email"]).first()
                form.username.data = dokter.name
                form.email.data = dokter.email
                form.speciality.data = dokter.speciality
                form.address.data = dokter.address
                if not dokter.image:
                    image_file = url_for("static", filename="karlo.jpg")
                else:
                    image_file = base64.b64encode(dokter.image).decode('ascii')
            else:
                pass
        elif form.validate_on_submit():
            if user == "val2":
                pasien = Patient.query.filter_by(email=session["email"]).first()
                pasien.name = form.username.data
                pasien.email = form.email.data
                pasien.gender = form.gender.data
                pasien.age = form.age.data
                pasien.address = form.address.data
                pasien.image = form.file_img.data.read()
                db.session.commit()
                flash("Data has been updated", "success")
                return redirect(url_for("main.account"))
            elif user == "val1":
                dokter = Doctor.query.filter_by(email=session["email"]).first()
                dokter.name = form.username.data
                dokter.email = form.email.data
                dokter.speciality = form.speciality.data
                dokter.address =form.address.data
                dokter.image = form.file_img.data.read()
                db.session.commit()
                flash("Data dokter sudah diupdata", "success")
                return redirect(url_for("main.account"))
            else:
                pass
        return render_template('mainapp/account.html', form=form, image_file=image_file)

@main.route("/appointment", methods=["POST", "GET"])
def appointment():
    if "email" in session:
        form = ExampleForm()
        form.dokters.choices = [ (str(dokter.id_doc), dokter.name) for dokter in Doctor.query.all()]
        if session["user"] == "val2":
            pasien = Patient.query.filter_by(email=session["email"]).first()
            if form.validate_on_submit():
                date = datetime.datetime.fromordinal(form.dt.data.toordinal())
                dokter = Doctor.query.filter_by(id_doc=int(form.dokters.data)).first()
                janji = Appointment(diagnosis='', treatment='', tanggal=date)
                dokter.app_docs.append(janji)
                pasien.app_pats.append(janji)
                db.session.add(janji)
                db.session.commit()
                flash(f"Appointment has been added!{dokter.name} {pasien.name} {date}")
            return render_template("mainapp/appointment.html", form=form)
        elif session["user"] == "val1":
            dokter = Doctor.query.filter_by(email=session["email"]).first()
            appointments = Appointment.query.filter_by(id_docter=dokter.id_doc).all()
            if appointments:
                return render_template("mainapp/docappointment.html", values=appointments)

    else:
        return redirect(url_for("auth.login"))

@main.route("/updatedata", methods=["GET", "POST"])
def updatedata():
    if request.method == "POST":
        appointment = Appointment.query.filter_by(id_app=request.form.get("id")).first()
        if appointment:
            appointment.diagnosis = request.form["diagnosa"]
            appointment.treatment = request.form["treat"]

            db.session.commit()
            flash(f"Data has been update!{request.form.get('id')}")
            return redirect(url_for("main.appointment"))

        

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/icofont/icofont.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/venobox/venobox.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/animate.css/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a href="#" class="navbar-brand">Call Me a Doctor!</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNoList" aria-controls="navbarNoList" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNoList">
          <div class="navbar-nav">
            <a href="#" class="nav-item nav-link active">Home <span class="sr-only">(current)</span></a>
            <a href="{{url_for('main.appointment')}}" class="nav-item nav-link">Appointment</a>
            <a href="{{url_for('main.docters')}}" class="nav-item nav-link">Doctors</a>
            <a href="{{url_for('main.account')}}" class="nav-item nav-link">Update Data</a>
            <a href="#" class="nav-item nav-link">Contact</a>
          </div>
          {% if g.user %}
            <a href="{{url_for('auth.logout')}}" class="navbar-brand ml-auto">Log Out</a>
          {% else %}
            <a href="{{url_for('auth.login')}}" class="navbar-brand ml-auto">Log In</a>
          {% endif %}
          </div>
        </div>
      </div>
    </header>

    <main>


<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block body %}{% endblock %}
</div>





     

    </main>

    <!-- jQuery first, then Bootstrap JS -->
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>


    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='assets/vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/jquery.easing/jquery.easing.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/php-email-form/validate.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/venobox/venobox.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/waypoints/jquery.waypoints.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/counterup/counterup.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/owl.carousel/owl.carousel.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>

    <!-- Template Main JS File -->
    <script src="{{ url_for('static', filename='assets/js/main.js')}}"></script>



  </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
    <h1>Hello {{g.user.name}}</h1>
{% endblock %}

app/templates/mainapp/account.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block title %}Account{% endblock %}
{% block body %}
<section id="doctors" class="doctors">
        <div class="col-lg-6">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="data:;base64,{{image_file}}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>{{ g.user.name }}</h4>
                <span>{{ g.user.email }}</span>
                <p>Explicabo voluptatem mollitia et repellat qui dolorum quasi</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>
    <div class='page-header'>
        <h1>Update</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form)}}
    </div>

</section>
{% endblock %}

app/templates/mainapp/appointment.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block title %}Appointment{% endblock %}
{% block body %}
<div class='page-header'>
        <h1>Appointment</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form)}}
    </div>
{% endblock %}

app/templates/mainapp/docappointment.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block title %}Appointment{% endblock %}
{% block body %}
<div class='page-header'>
        <h1>Appointment</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Pasien</th>
      <th scope="col">Diagnosa</th>
      <th scope="col">Treatment</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Update</th>


    </tr>
  </thead>
  <tbody>
  	{% for item in values %}
	    <tr>
	      <th scope="row">{{ loop.index }}</th>
	      <td>{{item.patient.name}}</td>
        <td>{{item.diagnosis}}</td>
        <td>{{item.treatment}}</td>
        <td>{{item.tanggal}}</td>
        <td><a href="/updatedata/{{ item.id_app }}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{ item.id_app }}">Edit</a> </td>
      </tr>
      
  <div class="modal fade" id="modaledit{{ item.id_app }}" role="dialog" >
    <div class="modal-dialog" >
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" >Treat {{ item.patient.name }}</h5>
          </div>
        <div class="modal-body">
          <form action="/updatedata" method="POST">
            <div class="form-group">
              <input type="hidden" name="id" value="{{item.id_app}}" >
              <label>Diagnosa:</label>
              <input type="text" class="form-control" name="diagnosa" value="{{item.diagnosis}}">
            </div>
            <div class="form-group">
              <label>Treatment:</label>
              <input type="text" class="form-control" name="treat" value="{{item.treatment}}">
            </div>
            <div class="form-group">
              <button class="btn btn-primary" type="submit">Update</button>
            </div>
          </form>
        </div>
              </div>
    </div>
  </div>



  	{% endfor %}
  </tbody>
</table>

{% endblock %}

app/templates/mainapp/docters.html
{% extends "base.html" %}
{% block title %}Docters{% endblock %}
{% block body %}
    <section id="doctors" class="doctors">
      <div class="container">

        <div class="section-title">
          <h2>Doctors</h2>
          <p>Ini dokter, kami siap melayani anda</p>
        </div>

        <div class="row">
          {% for dokter in dokters %}
          <div class="col-lg-6">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="data:;base64,{{ dokter.image }}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>{{dokter.name}}</h4>
                <span>{{dokter.speciality}}</span>
                <p>{{dokter.address}}</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>

      </div>
    </section><!-- End Doctors Section -->
{% endblock %}